name: "Nexora Telcom Multi-Account Terraform CI/CD"
on:
  pull_request:
    branches:
     - main
    paths:
     - 'environments/**'
     - 'modules/**'
    
  push:
    branches:
     - main
    paths:
     - 'environments/**'
     - 'modules/**'
jobs:
  terraform_ci:
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        environment: [tooling, prod]
    defaults:
      run:
        working-directory: environments/${{matrix.environment}}
    steps:
      - name: "Pull the repo to runner"
        uses: actions/checkout@v4
      - if: github.event_name == 'pull_request'
        run: |
          terraform fmt -check
          terraform init
          terraform validate
          terraform plan
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          terraform init
          terraform apply -auto-approve